inherits = "adwaita-dark"

"ui.background" = { bg = "base00" }
"ui.virtual" = "base03"
"ui.virtual.whitespace" = "base03"
"ui.virtual.jump-label" = { fg = "blue", modifiers = ["bold", "underlined"] }
"ui.virtual.ruler" = { bg = "base01" }
"ui.virtual.indent-guide" = { fg = "base01" }
"ui.menu" = { fg = "base05", bg = "base01" }
"ui.menu.selected" = { fg = "base01", bg = "base0A" }
"ui.linenr" = { fg = "base03", bg = "base00" }
"ui.popup" = { bg = "base01" }
"ui.window" = { bg = "base00", fg = "base02" }
"ui.linenr.selected" = { fg = "base04", bg = "base00", modifiers = ["bold"] }
"ui.selection" = { bg = "base02" }
"ui.selection.primary" = { bg = "selection_primary" }
"comment" = { fg = "base03", modifiers = ["italic"] }
"ui.statusline" = { fg = "base04", bg = "base01" }
'ui.statusline.inactive' = { bg = "base01", fg ="base03"}
"ui.statusline.normal" = { bg = "base04", fg = "base01"}
"ui.statusline.insert" = { bg = "base0B", fg = "base01"}
"ui.statusline.select" = { bg = "base0E", fg = "base01" }
"ui.cursor" = { bg = "base04" , fg="base00"}
"ui.cursor.primary.select" = { bg = "base0E" }
"ui.cursorline" = { bg = "base01" }
"ui.cursorline.primary" = { bg = "base01" }
"ui.cursorline.secondary" = { bg = "" }
"ui.cursor.primary" = { bg = "base05", fg="base01"}
"ui.text" = "base05"
"operator" = "base05"
"ui.text.focus" = "base05"
"variable" = "base05"
"variable.parameter" = "base08"
"variable.builtin" = "base08"
"constant.numeric" = "base09"
"constant.character" = "base08"
"constant" = "base09"
"attribute" = "base09"
"type" = "base0A"
"ui.cursor.match" = { fg = "base00", bg = "base03" }
"string"  = "base0B"
"variable.other.member" = "base0B"
"constant.character.escape" = "base0C"
"function" = "base11"
"constructor" = "base10"
"special" = "base0D"
"keyword" = "base0E"
"keyword.control" = "base0A"
"label" = "base0E"
"namespace" = "base0E"
"ui.help" = { fg = "base06", bg = "base01" }

"markup.heading" = "base0D"
"markup.heading.1" = "base0D"
"markup.heading.2" = "base11"
"markup.heading.3" = "base08"
"markup.heading.4" = "base09"
"markup.heading.5" = "base0E"
"markup.heading.6" = "base0B"
"markup.list" = "base08"
"markup.bold" = { fg = "base0A", modifiers = ["bold"] }
"markup.italic" = { fg = "base0E", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "base09", modifiers = ["underlined"] }
"markup.link.text" = "base08"
"markup.quote" = "base0C"
"markup.raw" = "base0B"

"diff.plus" = "base0B"
"diff.delta" = "base09"
"diff.minus" = "base08"

"diagnostic" = { modifiers = ["underlined"] }
"ui.gutter" = { bg = "base00" }
"info" = "base0E"
"hint" = "base0B"
"debug" = "base03"
"warning" = "base0A"
"error" = "base08"

"ui.bufferline" = { fg = "base04", bg = "base00" }
"ui.bufferline.active" = { fg = "base06", bg = "base01" }

'punctuation' = "base03"
'punctuation.delimiter' = "base03"
'punctuation.bracket' = "base03"


[palette]
base00 = "#212125" # Default Background
base01 = "#29292b" # Lighter Background (Used for status bars, line number and folding marks)
base02 = "#3f3f3f" # Selection Background
base03 = "#706f6e" # Comments, Invisibles, Line Highlighting
base04 = "#c0c0c0" # Dark Foreground (Used for status bars)
base05 = "#e0e0e0" # Default Foreground, Caret, Delimiters, Operators
base06 = "#e8e8e8" # Light Foreground (Not often used)
base07 = "#f8f8f8" # Light Background (Not often used)
base08 = "#f198b0" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
base09 = "#f5c2e7" # Integers, Boolean, Constants, XML Attributes, Markup Link Url
base0A = "#f9e2af" # Classes, Markup Bold, Search Text Background
base0B = "#b6e2b2" # Strings, Inherited Class, Markup Code, Diff Inserted
base0C = "#94e2d5" # Support, Regular Expressions, Escape Characters, Markup Quotes
base0D = "#f7e6c2" # Functions, Methods, Attribute IDs, Headings
base0E = "#aac3eb" # Keywords, Storage, Selector, Markup Italic, Diff Changed
base0F = "#a16946" # Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>
base10 = "#d6b0e6"
base11 = "#fac5a0"
selection_primary = "#33435C"

